# Generated by Django 6.0 on 2025-12-17 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balans (narxlashlar soni)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
                'db_table': 'bot_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tarif nomi')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxlashlar soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Narxi (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Narxlash tarifi',
                'verbose_name_plural': 'Narxlash tariflari',
                'db_table': 'pricing_tariffs',
                'ordering': ['count'],
            },
        ),
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=255, verbose_name='Telefon modeli')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Narxlangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='payments.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Narxlash tarixi',
                'verbose_name_plural': 'Narxlash tarixi',
                'db_table': 'pricing_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pricing_his_user_id_73cb11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Summa (so'm)")),
                ('pricing_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxlashlar soni')),
                ('payme_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Payme tranzaksiya ID')),
                ('state', models.IntegerField(choices=[(1, 'Yaratildi'), (2, "To'landi"), (-1, 'Bekor qilindi'), (-2, "To'lovdan keyin bekor qilindi")], db_index=True, default=1, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.botuser', verbose_name='Foydalanuvchi')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.pricingtariff', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='payments_state_f7e3a1_idx'), models.Index(fields=['user', 'state'], name='payments_user_id_0743fe_idx')],
            },
        ),
    ]
