# Generated by Django 6.0 on 2025-12-29 13:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True, verbose_name='Chek ID (Payme)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Summa (so'm)"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricing_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxlashlar soni'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='payments_order_i_b32b33_idx'),
        ),
    ]
