# Generated by Django 6.0 on 2026-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_order_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_create_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Payme create_time (ms)'),
        ),
    ]
