# Generated by Django 6.0 on 2026-01-05 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payme_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, verbose_name='Chek ID (Payme)'),
        ),
    ]
