# Generated by Django 6.0 on 2026-01-05 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Chek ID (Payme)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricing_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxlashlar soni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.botuser', verbose_name='Foydalanuvchi'),
        ),
    ]
