# Generated by Django 6.0 on 2026-01-05 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_order_id_alter_payment_pricing_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, verbose_name='Chek ID (Payme)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricing_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Narxlashlar soni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.botuser', verbose_name='Foydalanuvchi'),
            preserve_default=False,
        ),
    ]
