# Generated by Django 6.0 on 2026-01-05 12:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_order_id_alter_payment_pricing_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_state_f7e3a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_user_id_0743fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_order_i_b32b33_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='payme_cancel_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payme_perform_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payme_create_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payme_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pricing_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Yaratildi'), (2, "To'landi"), (-1, 'Bekor qilindi'), (-2, "To'lovdan keyin bekor qilindi")], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.pricingtariff'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.botuser'),
        ),
    ]
