# Generated by Django 6.0 on 2026-01-15 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='balance',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balans (narxlashlar soni)'),
        ),
    ]
