# Generated by Django 6.0 on 2026-01-15 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_botuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balans (narxlashlar soni)'),
        ),
    ]
